apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mojyc8gq0-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/mojyc8gq0-java-quarkus-gitops